// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./components/Camera.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonAvatar: typeof import('@ionic/vue')['IonAvatar']
    IonBackButton: typeof import('@ionic/vue')['IonBackButton']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCheckbox: typeof import('@ionic/vue')['IonCheckbox']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonImg: typeof import('@ionic/vue')['IonImg']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonListHeader: typeof import('@ionic/vue')['IonListHeader']
    IonModal: typeof import('@ionic/vue')['IonModal']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRadio: typeof import('@ionic/vue')['IonRadio']
    IonRadioGroup: typeof import('@ionic/vue')['IonRadioGroup']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSearchbar: typeof import('@ionic/vue')['IonSearchbar']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    ItemRow: typeof import('./components/ItemRow.vue')['default']
    Modal: typeof import('./pages/create-case/picture-preview.vue')['default']
    PictureModal: typeof import('./components/PictureModal.vue')['default']
    ReloadPWA: typeof import('./components/ReloadPWA.vue')['default']
    SubCategories: typeof import('./components/SubCategories.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
  }
}

export { }
