// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./components/Camera.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ItemRow: typeof import('./components/ItemRow.vue')['default']
    ReloadPWA: typeof import('./components/ReloadPWA.vue')['default']
    TextField: typeof import('./components/TextField.vue')['default']
  }
}

export { }
