global using System;
global using System.Threading;
global using System.Threading.Tasks;
global using AutoMapper;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Commentor.GivEtPraj.WebApi.Contracts.Requests;
global using Commentor.GivEtPraj.WebApi.Extensions;
global using Commentor.GivEtPraj.Application.Errors.Interfaces;